### ISSUE TITLE
Cannot install 1.3.1 on Python 3.6

### ISSUE THREAD

**Issue by ephracis** [bcwaldon/warlock#37]
Noticed you released a new version a couple of hours ago. It broke my CI which worked fine on 1.3.0. It still works on Python 2, though. Here is what I get:

```
[root@5005dfa6c983 /]# pip3 --version
pip 19.1.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@5005dfa6c983 /]# pip3 install -U warlock
Collecting warlock
  Using cached https://files.pythonhosted.org/packages/77/c6/48ad0aac045a477546709c952d12511f7f2291096caa4e6a3f558369f37d/warlock-1.3.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ocjuyama/warlock/setup.py", line 35, in <module>
        long_description=read("README.md"),
      File "/tmp/pip-install-ocjuyama/warlock/setup.py", line 28, in read
        return fp.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ocjuyama/warlock/
```

When I add `warlock==1.3.0` to my requirements.txt it works. There's something wrong with the new release.

**Comment by janw** [comment]
Hey @ephracis, sorry about that. Could you, for starters, set the following variables in the environment of your CI pipeline?

```shell
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

The error is most likely rooted in an incorrectly set up utf-8 environment. If that succeeds I'll be able to provide a fix in the project.

**Comment by janw** [comment]
I replicated the error locally by forcing ascii encoding on the files, so this is indeed the environment not being set up for utf-8. While I still think you @ephracis should check why that is the case (other things apart from Warlock's setup.py might break in the future), I will provide a fix to this particular issue in 1.3.2 within the hour.

**Comment by freddebacker** [comment]
My install is broken too for python2.7.

```Collecting warlock<2,>=1.2.0 (from python-glanceclient)
  Downloading https://files.pythonhosted.org/packages/7e/9b/648ceb3bc527e821c04d69f14facb0655268288ac7d8d6aa3a026c3316ea/warlock-1.3.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yl9AL5/warlock/setup.py", line 37, in <module>
        long_description=read("README.md"),
      File "/tmp/pip-install-yl9AL5/warlock/setup.py", line 28, in read
        os.path.join(os.path.dirname(__file__), fname), "r", encoding="utf-8"
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yl9AL5/warlock/
```

**Comment by ephracis** [comment]
I just tried to run `pip3 install -U warlock` and it worked fine. Got 1.3.2 so I guess your updated fixed the issue.
